version: '3'

services:
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - red-monitoreo

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    networks:
      - red-monitoreo

  zabbix-server:
    image: zabbix/zabbix-server-mysql
    ports:
      - "10051:10051"
    environment:
      DB_SERVER_HOST: zabbix-db
    networks:
      - red-monitoreo

  zabbix-db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: zabbix
    networks:
      - red-monitoreo

  zabbix-web:
    image: zabbix/zabbix-web-nginx-mysql
    ports:
      - "8080:8080"
    environment:
      DB_SERVER_HOST: zabbix-db
    networks:
      - red-monitoreo

networks:
  red-monitoreo:
    external: true

